target-version = "py314"

[lint]
select = ["ALL"]

ignore = [
    "ANN401", # Dynamically-typed expressions (typing.Any) are disallowed
    "D203",   # 1 blank line required before class docstring
    "D212",   # Multi-line docstring summary should start at the first line
    "COM812", # Trailing comma missing
    "ISC001", # Implicit string concatenation should be split across lines
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25
