[project]
name = "recteq"
version = "1.0.0"
description = "Recteq grill integration for Home Assistant"
requires-python = ">=3.14.2,<3.15"
dependencies = [
    "tinytuya==1.20.0",
]

[dependency-groups]
dev = [
    "colorlog==6.10.1",
    "homeassistant==2026.8.2",
    "ruff==0.15.21",
]

[tool.uv]
package = false
